//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PluginBehaviacJson.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PluginBehaviacJson.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 执行X次.
        /// </summary>
        internal static string CountOnce {
            get {
                return ResourceManager.GetString("CountOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 执行X次.
        /// </summary>
        internal static string CountOnceDesc {
            get {
                return ResourceManager.GetString("CountOnceDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 每X毫秒执行.
        /// </summary>
        internal static string EveryTime {
            get {
                return ResourceManager.GetString("EveryTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 每X毫秒执行.
        /// </summary>
        internal static string EveryTimeDesc {
            get {
                return ResourceManager.GetString("EveryTimeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExampleNode.
        /// </summary>
        internal static string ExampleNode {
            get {
                return ResourceManager.GetString("ExampleNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExampleNodeDesc.
        /// </summary>
        internal static string ExampleNodeDesc {
            get {
                return ResourceManager.GetString("ExampleNodeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExportFileWarning.
        /// </summary>
        internal static string ExportFileWarning {
            get {
                return ResourceManager.GetString("ExportFileWarning", resourceCulture);
            }
        }
    }
}
